<b>Steps to use NTS-Net</b>
1. Modifications to config:

  * FC_NUMS is the size of our classes in our training set

# Lesson 1 - What's your pet

In [0]:
from fastai.vision import *
from fastai.metrics import error_rate

In [0]:
!rm -r fastai_nts_net/

In [10]:
!git clone https://muellerzr:Dcsd128876!@github.com/muellerzr/fastai_nts_net.git

Cloning into 'fastai_nts_net'...
remote: Enumerating objects: 76, done.
remote: Counting objects: 100% (76/76), done.
remote: Compressing objects: 100% (75/75), done.
remote: Total 76 (delta 43), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (76/76), done.


In [0]:
#bs = 4
 bs = 4   # uncomment this line if you run out of memory even after clicking Kernel->Restart

In [0]:
# if we want to increase the batch size, we need to modify a few things in the model definition

In [0]:
path = untar_data(URLs.IMAGENETTE)

In [0]:
data = (ImageList.from_folder(path).split_by_folder(valid='val')
            .label_from_folder().transform(([flip_lr(p=0.5)], []), size=448)
            .databunch(bs=4, num_workers=2)
            .presize(448)
            .normalize(imagenet_stats))

In [10]:
data.c

10

In [0]:
from fastai_nts_net.model import *
from fastai_nts_net.prediction import *
from fastai_nts_net.loss_functions import *

# Train

In [0]:
net = attention_net(6, data.c, 4)

Verify last out_features = data.c

In [0]:
learn = Learner(data, net, loss_func=mytotal_loss, metrics=metric)

In [0]:
from fastai import *
from fastai.core import *
from fastai.vision import *
import fastai.metrics as metrics

from torch import sum
from torch.nn.functional import cross_entropy as CRE
from torch.nn.functional import relu
from torch.autograd import Variable
def mytotal_loss(out, label):
    bs = learn.data.batch_size
    
    raw_logits, concat_logits, part_logits, _, top_n_prob = out
    
    lbl = label.unsqueeze(1).repeat(1, 6).view(-1)
    lgt = part_logits.view(bs * 6, -1)
    
    part_loss = list_loss(lgt, lbl).view(bs,6)
    raw_loss = CRE(raw_logits, label)
    concat_loss = CRE(concat_logits, label)
    rank_loss = ranking_loss(top_n_prob, part_loss, 6)
    partcls_loss = CRE(lgt, lbl)
    
    total_loss = rank_loss + raw_loss + concat_loss + partcls_loss
    return total_loss.squeeze(0)

In [16]:
learn.fit(1)

# Predictions

In [0]:
img = open_image(path/'train/n02102040/n02102040_811.JPEG')

In [21]:
custom_prediction(learn, img)

(Image (3, 448, 448),
 Category n01440764,
 tensor(0),
 [tensor([-0.1047, -0.1354, -0.8370, -0.3982, -0.4538, -0.3667, -0.5409, -0.4704,
          -0.2186, -0.5526]),
  tensor([-0.5880, -0.7730, -1.1386, -1.0290, -1.1853, -1.1163, -1.1625, -1.1812,
          -0.8291, -1.1384]),
  tensor([[ 0.0211, -0.1520, -0.2445, -0.2559, -0.1893, -0.0617, -0.1277, -0.1775,
           -0.1742, -0.2338],
          [-0.0668, -0.2908, -0.3265, -0.4114, -0.3098, -0.3217, -0.1883, -0.2683,
           -0.2625, -0.0887],
          [ 0.0190, -0.0618, -0.1629, -0.1917, -0.1537, -0.0725, -0.0740, -0.1171,
           -0.1564, -0.3391],
          [ 0.0160, -0.1561, -0.1628, -0.2380, -0.1949, -0.0273, -0.0965, -0.1578,
           -0.2203, -0.3296],
          [-0.0237, -0.1102, -0.1664, -0.1905, -0.1926, -0.0543, -0.0785, -0.1492,
           -0.1401, -0.1722],
          [-3.6370, -5.3947, -3.5158, -4.2635, -2.9056, -5.4393, -2.0241, -2.4829,
           -4.9897, -1.5583]]),
  tensor([648, 684, 707, 692, 633, 597]),

In [0]:
def custom_prediction(learn:Learner, item:ItemBase):
  batch = learn.data.one_item(item)
  res = learn.pred_batch(batch=batch)
  raw_pred, x = grab_idx(res, 0),batch[0]
  norm = getattr(learn.data, 'norm', False)
  if norm:
    x = learn.data.denorm(x)
    if norm.keywords.get('do_y', False): pred = learn.data.denorm(pred)
  ds = learn.data.single_ds
  pred = get_pred(pred=raw_pred)
  out = ds.y.reconstruct(pred, ds.x.reconstruct(img.data)) if has_arg(ds.y.reconstruct, 'x') else ds.y.reconstruct(pred)
  x = ds.x.reconstruct(grab_idx(x, 0))
  y = ds.y.reconstruct(pred, x)  if has_arg(ds.y.reconstruct, 'x') else ds.y.reconstruct(pred)
  return (x, y, pred, raw_pred)

In [0]:
from fastai.core import *

In [0]:
ItemBase

fastai.core.ItemBase

In [0]:
def get_pred(pred): 
  _, concat_logits, _, _, _ = pred
  return concat_logits.argmax()